# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runMCMC <- function(modoptions, data, nsims, nburn = 0L, nmetro = 10L, forward = FALSE, cheat = FALSE, outputfinal = FALSE, outputparam = TRUE, verbose = FALSE) {
    .Call(`_bayestransmission_runMCMC`, modoptions, data, nsims, nburn, nmetro, forward, cheat, outputfinal, outputparam, verbose)
}

hello_world <- function() {
    invisible(.Call(`_bayestransmission_hello_world`))
}

