# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

runMCMC <- function(modname, data, MCMCParameters, modelParameters, nstates = 2L, verbose = FALSE) {
  .Call(`_bayestransmission_runMCMC`, modname, data, MCMCParameters, modelParameters, nstates, verbose)
}

hello_world <- function() {
  invisible(.Call(`_bayestransmission_hello_world`))
}
