# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

CodeToEvent <- function(x) {
    .Call(`_bayestransmission_CodeToEvent`, x)
}

#' Convert string events to coded events
#' @param x A vector of strings
#'
#' @return A vector of integers
#'
#' @export
EventToCode <- function(x) {
    .Call(`_bayestransmission_EventToCode`, x)
}

#' Run Bayesian Transmission MCMC
#'
#' @param modname Name of the model to run.
#' @param data Data frame with columns, in order: facility, unit, time, patient, and event type.
#' @param MCMCParameters List of MCMC parameters.
#' @param modelParameters List of model parameters, see <LogNormalModelParams>.
#' @param nstates Number of states in the model.
#' @param verbose Print progress messages.
#'
#' @return A list with the following elements:
#'   * `Parameters` the MCMC chain of model parameters
#'   * `LogLikelihood` the log likelihood of the model at each iteration
#'   * `MCMCParameters` the MCMC parameters used
#'   * `ModelParameters` the model parameters used
#'   * `ModelName` the name of the model
#'   * `nstates` the number of states in the model
#'   * `waic1` the WAIC1 estimate
#'   * `waic2` the WAIC2 estimate
#'   * and optionally (if `MCMCParameters$outputfinal` is true) `FinalModel` the final model state.
#' @export
runMCMC <- function(modname, data, MCMCParameters, modelParameters, nstates = 2L, verbose = FALSE) {
    .Call(`_bayestransmission_runMCMC`, modname, data, MCMCParameters, modelParameters, nstates, verbose)
}

hello_world <- function() {
    invisible(.Call(`_bayestransmission_hello_world`))
}

